from alphazero.bubble_board import BubbleBoard

board = BubbleBoard(board_len=5)


board.do_action_print((0, 1))
board.do_action_print((3, 3))
board.do_action_print((0, 1))
board.do_action_print((3, 3))

board.do_action_print((0, 0))
board.do_action_print((4, 4))
board.do_action_print((0, 0))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
board.do_action_print((0, 1))
board.do_action_print((4, 4))
